In [8]:
def test():
    print("test() for function")
    return
test()

test() for function


In [7]:
#object oriented programming
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for the class and method


In [20]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)

120

In [32]:
#method
#def test(self,paral,paraz)
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
     
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))



300


In [25]:
#some inheritance
class person(object):
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemploye(self):
        return False
    
    #derived class
class employe(person):
        def isemploye(self):
            return True
emp=person("sri")
print(emp.getname(),emp.isemploye())
emp1=employe("sri")
print(emp1.getname(),emp1.isemploye())

sri False
sri True


In [7]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [8]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)

(4,)


In [9]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array.dtype)

int32


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [11]:
##re shape the given array
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
##append same data---horizantally
##append same data---vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [18]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [24]:
#generate random no from np
a1=np.random.normal([(5,0,5,10)])
print(a1)

[[ 6.50643765 -0.89398665  3.63660418  9.16971175]]


In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [34]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [12]:
import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [11]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("secondrow :",a1[1])

secondrow : [4 5 6]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicingrow coloumn :",a1[:,1])

slicingrow coloumn : [2 5]


In [22]:
a1=np.array([(1,2,3),[4,5,6]])
print("slicing last coloumn ",a1[:,2])

slicing last coloumn  [3 6]


In [21]:
a1=np.array([(1,2,3),[4,5,6]])
print("row and coloumn",a1[1:,2])

row and coloumn [6]


In [23]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value= ",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.08387837 4.34460358 4.20436284 6.46268734 2.34505318 6.87762523
 4.97453211 4.43507819 6.08159573 4.93877097]
min value=  2.3450531756857274
max value= 6.877625231451633
mean value= 4.974818753094382
median value= 4.956651536032418


In [24]:
##multiply of 1d arrays
#numpy.dot(x,y)
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [27]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [40]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [8]:

import pandas as pd
dict1 ={"name":["anil","sri","praven","lucky","sri","kanth"],"emailid":["anil@gmail.com","sri@gmail.com","praven@gmail.com","lucky@gmail.com","sri@gmail.com","kanth@gmail.com"],"mobilenumber":[879,564,213,546,864,856],"address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict1)
print(b)



     name           emailid  mobilenumber address
0    anil    anil@gmail.com           879     hyd
1     sri     sri@gmail.com           564     hyd
2  praven  praven@gmail.com           213     hyd
3   lucky   lucky@gmail.com           546     hyd
4     sri     sri@gmail.com           864     hyd
5   kanth   kanth@gmail.com           856     hyd


In [11]:
b.index=["01","02","03","04","05","06"]
print(b)

      name           emailid  mobilenumber address
01    anil    anil@gmail.com           879     hyd
02     sri     sri@gmail.com           564     hyd
03  praven  praven@gmail.com           213     hyd
04   lucky   lucky@gmail.com           546     hyd
05     sri     sri@gmail.com           864     hyd
06   kanth   kanth@gmail.com           856     hyd
